// Code generated by mockery v2.11.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	testing "testing"
)

// DoService is an autogenerated mock type for the DoService type
type DoService struct {
	mock.Mock
}

// Do provides a mock function with given fields:
func (_m *DoService) Do() (bool, error) {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewDoService creates a new instance of DoService. It also registers a cleanup function to assert the mocks expectations.
func NewDoService(t testing.TB) *DoService {
	mock := &DoService{}

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
